### PR TITLE
ospf regex - n7k

### PR DESCRIPTION
**Pull request by seismiccollision**
added regex to handle the following from a nexus 7k

%OSPF-5-NBRSTATE:  ospf-11 [7674]  Process 11, Nbr 1.1.1.1 on Vlan50 from EXCHANGE to FULL, EXCHDONE
%OSPF-5-NBRSTATE:  ospf-11 [7708]  Process 11, Nbr 1.1.1.1 on Vlan50 from EXSTART to EXCHANGE, NEGDONE

### CODE REVIEW

**Comment by inspired** [comment]
Thanks!

**Comment by seismiccollision** [comment]
Hey,
Hope things are going well for you

I'm trying to come up with a way to handle syslogs from Cisco APs so I can
add views into the wireless dashboard but I can't find a good way to
distinguish them as an event type
here's a sample of what I'm getting:
May  7 10:10:10 10.10.0.154 61: AP:7cad.7428.3ddb: *May  7 17:10:10.731:
%LINK-6-UPDOWN: Interface Dot11Radio1, changed state to down
May  7 10:10:10 10.10.0.154 60: AP:7cad.7428.3ddb: *May  7 17:10:09.739:
%WIDS-6-DISABLED: IDS Signature is removed and disabled.
May  7 10:10:10 10.10.0.154 59: AP:7cad.7428.3ddb: *May  7 17:10:09.679:
%WIDS-6-ENABLED: IDS Signature is loaded and enabled
May  7 10:07:12 10.10.0.140 132: AP:6c41.6aa3.41e5: *May  7 17:07:10.227:
%DOT11-4-CCMP_REPLAY: Client 78fd.9494.e4b7 had 1 AES-CCMP TSC replays
May  7 10:07:05 10.10.0.140 131: AP:6c41.6aa3.41e5: *May  7 17:07:03.227:
%DOT11-4-CCMP_REPLAY: Client 78fd.9494.e4b7 had 1 AES-CCMP TSC replays
May  7 10:55:53 10.10.0.150 75: AP:7cad.7418.b0c5: *May  7 17:55:51.531:
%DOT11-4-CCMP_REPLAY: Client 3436.3bcf.4c68 had 1 AES-CCMP TSC replays
May  7 10:31:14 10.10.0.139 99: AP:6c41.6aca.3e9f: *May  7 17:31:13.623:
%LINEPROTO-5-UPDOWN: Line protocol on Interface Dot11Radio1, changed state
to up
May  7 10:31:13 10.10.0.139 98: AP:6c41.6aca.3e9f: *May  7 17:31:12.623:
%LINK-6-UPDOWN: Interface Dot11Radio1, changed state to up
May  7 10:31:13 10.10.0.139 97: AP:6c41.6aca.3e9f: *May  7 17:31:12.619:
%DOT11-6-DFS_SCAN_START: DFS: Scanning frequency 5320 MHz for 60 seconds.
May  7 10:31:12 10.10.0.139 96: AP:6c41.6aca.3e9f: *May  7 17:31:12.603:
%LINEPROTO-5-UPDOWN: Line protocol on Interface Dot11Radio1, changed state
to down
May  7 10:31:12 10.10.0.139 95: AP:6c41.6aca.3e9f: *May  7 17:31:11.599:
%LINK-5-CHANGED: Interface Dot11Radio1, changed state to reset
May  7 10:31:11 10.10.0.139 94: AP:6c41.6aca.3e9f: *May  7 17:31:11.595:
%LINK-6-UPDOWN: Interface Dot11Radio1, changed state to down

the only thing that makes them unique seems to be "AP:<ethernet_mac>:" but
I'm not sure if it makes sense to pull ethernet_mac out of the parent
eventtype
any thoughts/ideas?
Thanks!
-David

**Comment by inspired** [comment]
Hey!

Doing great, thanks.

Are these autonomous access points?

So all of the events coming from the APs have the AP:... string in them? Is
anything catched by the regex? I could probably throw in a regex match for
the AP:... stuff in the general regex. It's going to make it look uglier
thsn it already is, but it makes for a cool feature. I could then populate
the product field with a value of "AP" or similar which makes it easy for
you to pick AP events for the wireless dashboard :-)

I'll test the regex stuff tomorrow. Just confirm if my suggestions make
sense.

Thanks a lot for helping me with this by the way!

Mikael
7. mai 2015 20.30 skrev "seismiccollision" notifications@github.com:

**Comment by seismiccollision** [comment]
Hey Mikael,
the APs are actually lightweight APs (not autonomous mode) but from the WLC
you can issue the following CLI-only commands to get the APs to
individually syslog:
config ap syslog host global <IP Address>
config ap logging syslog level information all

if you have a WLC and don't configure the AP syslog destination the APs
will still syslog at a default verbosity to broadcast IP
i was messing with maybe something like the following
sourcetype=cisco:ios | rex
"AP:(?<ap_mac>[0-9a-fA-F]{4}.[0-9a-fA-F]{4}.[0-9a-fA-F]{4}):"

from there it may even be possible to setup some little snmp query against
a wireless controller to tie the AP mac addresses to their names in a
lookup:
snmpwalk -v 2c -c pubic <wlc_ip> 1.3.6.1.4.1.9.9.513.1.1.1.1.2
snmpwalk -v 2c -c pubic <wlc_ip> 1.3.6.1.4.1.9.9.513.1.1.1.1.5

I had been trying to make something useful in Splunk for our Cisco
environment with small successes but you really took it to the next level
so I'm always happy to help
Thank you!
-David

**Comment by inspired** [comment]
Can you try the latest dev version now? product can now get a value of AP
if the direct_ap_mac field exists. I'll add this as a selector in the
overview page if it works as expected. Let me know if anything else breaks,
ok? :-)

2015-05-08 1:24 GMT+02:00 seismiccollision notifications@github.com:

> Hey Mikael,
> the APs are actually lightweight APs (not autonomous mode) but from the WLC
> you can issue the following CLI-only commands to get the APs to
> individually syslog:
> config ap syslog host global <IP Address>
> config ap logging syslog level information all
> 
> if you have a WLC and don't configure the AP syslog destination the APs
> will still syslog at a default verbosity to broadcast IP
> i was messing with maybe something like the following
> sourcetype=cisco:ios | rex
> "AP:(?<ap_mac>[0-9a-fA-F]{4}.[0-9a-fA-F]{4}.[0-9a-fA-F]{4}):"
> 
> from there it may even be possible to setup some little snmp query against
> a wireless controller to tie the AP mac addresses to their names in a
> lookup:
> snmpwalk -v 2c -c pubic <wlc_ip> 1.3.6.1.4.1.9.9.513.1.1.1.1.2
> snmpwalk -v 2c -c pubic <wlc_ip> 1.3.6.1.4.1.9.9.513.1.1.1.1.5
> 
> I had been trying to make something useful in Splunk for our Cisco
> environment with small successes but you really took it to the next level
> so I'm always happy to help
> Thank you!
> -David
> 
> On Thu, May 7, 2015 at 1:13 PM, inspired notifications@github.com wrote:
> 
> > Hey!
> > 
> > Doing great, thanks.
> > 
> > Are these autonomous access points?
> > 
> > So all of the events coming from the APs have the AP:... string in them?
> > Is
> > anything catched by the regex? I could probably throw in a regex match
> > for
> > the AP:... stuff in the general regex. It's going to make it look uglier
> > thsn it already is, but it makes for a cool feature. I could then
> > populate
> > the product field with a value of "AP" or similar which makes it easy for
> > you to pick AP events for the wireless dashboard :-)
> > 
> > I'll test the regex stuff tomorrow. Just confirm if my suggestions make
> > sense.
> > 
> > Thanks a lot for helping me with this by the way!
> > 
> > Mikael
> > 1. mai 2015 20.30 skrev "seismiccollision" notifications@github.com:
> > 
> > > Hey,
> > > Hope things are going well for you
> > > 
> > > I'm trying to come up with a way to handle syslogs from Cisco APs so I
> > > can
> > > add views into the wireless dashboard but I can't find a good way to
> > > distinguish them as an event type
> > > here's a sample of what I'm getting:
> > > May 7 10:10:10 10.10.0.154 61: AP:7cad.7428.3ddb: *May 7 17:10:10.731:
> > > %LINK-6-UPDOWN: Interface Dot11Radio1, changed state to down
> > > May 7 10:10:10 10.10.0.154 60: AP:7cad.7428.3ddb: *May 7 17:10:09.739:
> > > %WIDS-6-DISABLED: IDS Signature is removed and disabled.
> > > May 7 10:10:10 10.10.0.154 59: AP:7cad.7428.3ddb: *May 7 17:10:09.679:
> > > %WIDS-6-ENABLED: IDS Signature is loaded and enabled
> > > May 7 10:07:12 10.10.0.140 132: AP:6c41.6aa3.41e5: *May 7 17:07:10.227:
> > > %DOT11-4-CCMP_REPLAY: Client 78fd.9494.e4b7 had 1 AES-CCMP TSC replays
> > > May 7 10:07:05 10.10.0.140 131: AP:6c41.6aa3.41e5: *May 7 17:07:03.227:
> > > %DOT11-4-CCMP_REPLAY: Client 78fd.9494.e4b7 had 1 AES-CCMP TSC replays
> > > May 7 10:55:53 10.10.0.150 75: AP:7cad.7418.b0c5: *May 7 17:55:51.531:
> > > %DOT11-4-CCMP_REPLAY: Client 3436.3bcf.4c68 had 1 AES-CCMP TSC replays
> > > May 7 10:31:14 10.10.0.139 99: AP:6c41.6aca.3e9f: *May 7 17:31:13.623:
> > > %LINEPROTO-5-UPDOWN: Line protocol on Interface Dot11Radio1, changed
> > > state
> > > to up
> > > May 7 10:31:13 10.10.0.139 98: AP:6c41.6aca.3e9f: *May 7 17:31:12.623:
> > > %LINK-6-UPDOWN: Interface Dot11Radio1, changed state to up
> > > May 7 10:31:13 10.10.0.139 97: AP:6c41.6aca.3e9f: *May 7 17:31:12.619:
> > > %DOT11-6-DFS_SCAN_START: DFS: Scanning frequency 5320 MHz for 60
> > > seconds.
> > > May 7 10:31:12 10.10.0.139 96: AP:6c41.6aca.3e9f: *May 7 17:31:12.603:
> > > %LINEPROTO-5-UPDOWN: Line protocol on Interface Dot11Radio1, changed
> > > state
> > > to down
> > > May 7 10:31:12 10.10.0.139 95: AP:6c41.6aca.3e9f: *May 7 17:31:11.599:
> > > %LINK-5-CHANGED: Interface Dot11Radio1, changed state to reset
> > > May 7 10:31:11 10.10.0.139 94: AP:6c41.6aca.3e9f: *May 7 17:31:11.595:
> > > %LINK-6-UPDOWN: Interface Dot11Radio1, changed state to down
> > > 
> > > the only thing that makes them unique seems to be "AP:<ethernet_mac>:"
> > > but
> > > I'm not sure if it makes sense to pull ethernet_mac out of the parent
> > > eventtype
> > > any thoughts/ideas?
> > > Thanks!
> > > -David
> > > 
> > > On Wed, Mar 25, 2015 at 10:49 PM, inspired notifications@github.com
> > > wrote:
> > > 
> > > > Merged #3 https://github.com/inspired/TA-cisco_ios/pull/3.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/inspired/TA-cisco_ios/pull/3#event-265500330.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/inspired/TA-cisco_ios/pull/3#issuecomment-99969481
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/inspired/TA-cisco_ios/pull/3#issuecomment-100003856
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/inspired/TA-cisco_ios/pull/3#issuecomment-100045730.

## 

Hug a tree before you print this e-mail

**Comment by seismiccollision** [comment]
Just got it updated this morning - so far it seems to be working as
expected, thanks!
-David

**Comment by inspired** [comment]
Great! Did you also update the main app to get the toggle in the overview
page?

Out of curiousity - how many devices do you have logging Cisco IOS/WLC/AP
data?

I've seen degraded performance in the data model driven dashboards after
including the toggle to filter based on Cisco_IOS_Event.product. It would
be nice if you could have a look at it. I've only had the chance to test it
at two customer installations. One with about 300 devices and the other
with about 950. The acceleration period is 7 days and most of the data is
fetched quickly, but the latest hours seem to take longer time to show up.
I wonder if the filter is super slow on data that hasn't been accelerated
yet.
11. mai 2015 17.46 skrev "seismiccollision" notifications@github.com:

> Just got it updated this morning - so far it seems to be working as
> expected, thanks!
> -David
>

**Comment by seismiccollision** [comment]
Hey! Yup, we have the main app updated
Sadly we only have 25 APs.. I'll see if I can use what I have to gather any
data.. My last job had >900 - I can reach out and see if they might be
willing to test

**Pull request merged**
